# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  buildConfiguration: 'Release'

pool:
  #vmImage: ubuntu-latest
  name: Default

steps:
#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'build'
#    arguments: '--configuration $(buildConfiguration)'
#  displayName: 'Build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
  displayName: 'Publish $(buildConfiguration)'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'FastCarzApi'
  displayName: Publish pipeline artifacts

- task: Docker@2
  inputs:
    repository: 'FastCarzApi'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
  displayName: Build Docker image
#- task: Bash@3
#  inputs:
#    targetType: 'inline'
#    script: 'docker run -d -p 9082:80 --name FastCarzApi fastcarzapi:$(Build.BuildId)'
- task: PowerShell@2
  displayName: Run a container
  inputs:
    targetType: 'inline'
    script: |
      docker run -d -p 9082:80 --name FastCarzApi fastcarzapi:$(Build.BuildId)
#- task: Bash@3
#  inputs:
#    targetType: 'inline'
#    script: 'curl http://localhost:9082/WeatherForecast'

- task: PowerShell@2
  displayName: Check endpoint
  inputs:
    targetType: 'inline'
    script: |
      curl http://localhost:9082/WeatherForecast

- task: PowerShell@2
  displayName: Remove container
  inputs:
    targetType: 'inline'
    script: |
     docker rm -f FastCarzApi
  condition: always()